swagger: '2.0'

info:
  title: mint API
  version: '0.1'
  description: mint is STUPS' secret rotator and distributor.

externalDocs:
  description: STUPS documentation
  url: http://stups.readthedocs.org/

basePath: /
produces:
- application/json
consumes:
- application/json

paths:

  '/apps':
    get:
      summary: list managed applications
      description: |
        Provides a list of all applications, that are managed by mint.
      tags:
        - Application
      operationId: undefined
      responses:
        200:
          description: list of managed applications
          schema:
            description: all applications
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                last_password_rotation:
                  type: string
                  format: date-time
                last_client_rotation:
                  type: string
                  format: date-time
                has_problems:
                  type: boolean
              required:
                - id
                - has_problems
          examples:
            application/json:
              - id: pierone
                last_password_rotation: "2015-06-14T15:30:00Z+01:00"
                last_client_rotation:
                has_problems: false
        default:
          $ref: '#/responses/Error'

  '/apps/{application_id}':
    get:
      summary: read application
      description: |
        Returns state and configuration information about an application.
      tags:
        - Application
      operationId: undefined
      parameters:
        - $ref: '#/parameters/ApplicationID'
      responses:
        200:
          description: application information
          schema:
            type: object
            properties:
              id:
                type: string
              last_password_rotation:
                type: string
                format: date-time
              last_client_rotation:
                type: string
                format: date-time
              has_problems:
                type: boolean
              accounts:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
              redirect_urls:
                type: array
                items:
                  type: string
            required:
              - id
              - has_problems
              - accounts
        default:
          $ref: '#/responses/Error'

    put:
      summary: create or update configuration
      description: |
        Creates or updates the application's configuration. If no accounts are listed, the configuration will be
        deleted.
      tags:
        - Application
      operationId: undefined
      parameters:
        - $ref: '#/parameters/ApplicationID'
        - name: application
          in: body
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
              redirect_urls:
                type: array
                items:
                  type: string
      responses:
        200:
          description: configuration stored
        default:
          $ref: '#/responses/Error'

    patch:
      summary: update configuration status
      description: |
        Updates the application's configuration status.
      tags:
        - Status
      operationId: undefined
      parameters:
        - $ref: '#/parameters/ApplicationID'
        - name: status
          in: body
          schema:
            type: object
            properties:
              client_id:
                type: string
              last_password_rotation:
                type: string
                format: date-time
              last_client_rotation:
                type: string
                format: date-time
              has_problems:
                type: boolean
      responses:
        200:
          description: configuration status updated
        default:
          $ref: '#/responses/Error'

    delete:
      summary: delete application configuration
      description: |
        Deletes an application configuration. Has the same effect than passing an empty account list to the PUT request.
      tags:
        - Application
      operationId: undefined
      parameters:
        - $ref: '#/parameters/ApplicationID'
      responses:
        200:
          description: configuration deleted
        default:
          $ref: '#/responses/Error'

parameters:
  ApplicationID:
    name: application_id
    in: path
    type: string
    description: ID of the application
    required: true

responses:
  Error:
    description: An error occured.
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    example:
      message: Internal Server Error
